pre-release fixes: btg-daemon.init: increased daemon termination wait timeout to 1 minute btg-daemon.preinst: more fancy existing config file backup reporting Makefile.am: added build.sh to the dist context.cpp: LT-12 compilation fix, comments peertreeview.cpp: more algorithmic code mainmodel.h: missed comment for class member mainwindow.cpp: increased the visible range y 1 - more ergonomic look buildbot.sh: added Fails/Warnings/Errors counters to the subject

diff --git a/trunk/debian/btg-daemon.init b/trunk/debian/btg-daemon.init
--- a/trunk/debian/btg-daemon.init
+++ b/trunk/debian/btg-daemon.init
@@ -39,7 +39,7 @@ case $1 in
 		echo -n "."
 		cnt=$(($cnt+1))
 	done
-	[ $cnt -ge 30 ] && echo "ERROR. You can wait or kill it yourself." || echo "DONE"
+	[ $cnt -ge 60 ] && echo "ERROR. You can wait or kill it yourself." || echo "DONE"
     ;;
     restart|reload|force-reload)
     	echo "Not implemented yet."
diff --git a/trunk/debian/btg-daemon.preinst b/trunk/debian/btg-daemon.preinst
--- a/trunk/debian/btg-daemon.preinst
+++ b/trunk/debian/btg-daemon.preinst
@@ -2,8 +2,11 @@
 
 # $Id$
 
-# backup default config data
-cp -f /var/lib/btg/auth /var/lib/btg/auth.bak
-cp -f /var/lib/btg/sessions /var/lib/btg/sessions.bak
+# backup existent config data
+for file in /var/lib/btg/auth /var/lib/btg/sessions ; do
+	echo -n "Backupping config file $file ..."
+	cp -f $file $file.bak && echo "OK" || echo "error/skipped"
+done
+true # discard any errors
 
 #DEBHELPER#
